export const FETCH_DATA_START = 'FETCH_DATA_START';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILED = 'FETCH_DATA_FAILED';

export const SET_DATA = 'SET_DATA';
export const SELECTED_BREWER = 'SELECTED_BREWER';
