export const FETCH_DATA_START = 'FETCH_DATA_START';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILED = 'FETCH_DATA_FAILED';

export const SET_DATA = 'SET_DATA';
export const SELECTED_BREWER = 'SELECTED_BREWER';
export const SELECTED_BREWER2 = 'SELECTED_BREWER2';
export const SELECTED_BREWER3 = 'SELECTED_BREWER3';

export const THEME_CHANGE = 'THEME_CHANGE';
export const LIMIT_CHANGE = 'LIMIT_CHANGE';
export const SORT_CHANGE = 'SORT_CHANGE';
